/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-03-22 04:08:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("        <style>\n");
      out.write("        div.result {\n");
      out.write("            margin: auto;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("            text-align: center;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        label,\n");
      out.write("        input,\n");
      out.write("        button {\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table,\n");
      out.write("        td {\n");
      out.write("            border: 1px solid #317c31;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("            padding: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        h3 {\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        label {\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        input[type=\"submit\"],input[type=\"reset\"] {\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            background-color: #317c31;\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            margin: auto;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        #btn1{\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            background-color: lime;\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            margin: auto;\n");
      out.write("            font-weight: bold;\n");
      out.write("       }\n");
      out.write("       </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <h3>Registration Form</h3>\n");
      out.write("    <div class=\"result\">\n");
      out.write("         ");
 if("correct".equals(request.getAttribute("insertst"))) {
      out.write("\n");
      out.write("            <script>\n");
      out.write("                alert(\"Data submitted successfully!\");\n");
      out.write("            </script>\n");
      out.write("        ");
}
      out.write("\n");
      out.write("        <form name=\"registration\" method=\"get\" action=\"UserDatabase\"  onsubmit=\"return validateForm()\">\n");
      out.write("            \n");
      out.write("            <table>\n");
      out.write("                <tr>\n");
      out.write("                    <td>\n");
      out.write("                        <label for=\"first_name\">First Name:</label>\n");
      out.write("                    </td>\n");
      out.write("                    <td>\n");
      out.write("                        <input type=\"text\" id=\"first_name\"  placeholder=\"Enter Your First Name\" name=\"first_name\" onfocusout=\"FristNameValid()\">\n");
      out.write("                        <span id=\"error1\" class=\"red\"></span>\n");
      out.write("                    </td>\n");
      out.write("\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>\n");
      out.write("                        <label for=\"last_name\">Last Name:</label>\n");
      out.write("                    </td>\n");
      out.write("                    <td>\n");
      out.write("                        <input type=\"text\" id=\"last_name\" placeholder=\"Enter Your Second Name\" name=\"last_name\" onfocusout=\"SecondNameValid()\">\n");
      out.write("                        <span id=\"error2\" class=\"red\"></span>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>\n");
      out.write("                        <label for=\"email\">Email:</label>\n");
      out.write("                    </td>\n");
      out.write("                    <td>\n");
      out.write("                        <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"Enter Your Email Id\" onfocusout=\"EmailValid()\">\n");
      out.write("                        <span id=\"error3\" class=\"red\"></span>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>\n");
      out.write("                        <label for=\"Password\">Password </label>\n");
      out.write("                    </td>\n");
      out.write("                    <td>\n");
      out.write("                        <input type=\"password\" id=\"Password\" placeholder=\"Password less then 6 characters\" name=\"Password\" onfocusout=\"PassValid()\">\n");
      out.write("                        <span id=\"error4\" class=\"red\"></span>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>\n");
      out.write("                        <label for=\"ConformPassword\">Conform Password </label>\n");
      out.write("                    </td>\n");
      out.write("                    <td>\n");
      out.write("                        <input type=\"password\" id=\"Conform\" placeholder=\"ReEnter Password\" name=\"Password\" onfocusout=\"SemPassValid()\">\n");
      out.write("                        <span id=\"error5\" class=\"red\"></span>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>\n");
      out.write("                        <label for=\"Number\">Mobile Number</label>\n");
      out.write("                    </td>\n");
      out.write("                    <td>\n");
      out.write("                        <input type=\"text\" id=\"Number\" name=\"Number\" onfocusout=\"NumberValid()\">\n");
      out.write("                        <span id=\"error6\" class=\"red\"></span>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>\n");
      out.write("                    <label for=\"add\">Address</label><br>\n");
      out.write("                </td>\n");
      out.write("\n");
      out.write("                <td>\n");
      out.write("                    <textarea name=\"add\" id=\"add\" cols=\"30\" rows=\"5\" required></textarea>\n");
      out.write("                     <span id=\"error7\" class=\"red\"></span>    \n");
      out.write("                </td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                <td>\n");
      out.write("                    <label for=\"Role\">Choose a Role:</label>\n");
      out.write("                </td>\n");
      out.write("                <td>\n");
      out.write("                    <select name=\"Role\" id=\"res\" required>\n");
      out.write("\n");
      out.write("                        <option value=\"\">Selcect Option</option>\n");
      out.write("                        <option value=\"101\">Admin</option>\n");
      out.write("                        <option value=\"102\">Registered User</option>\n");
      out.write("                        <option value=\"103\">Guest </option>\n");
      out.write("                  \n");
      out.write("                    </select>\n");
      out.write("                    <span id=\"error5\" class=\"red\"></span>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                   <td><input type=\"reset\" value=\"Reset\" name=\"reset\"></td> <td colspan=\"2\"><input type=\"submit\" value=\"Register\" name=\"submit\"></td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("            </table>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("         var emailRegex = /^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$/;\n");
      out.write("         var nameRegex = /^[A-Za-z]+$/;\n");
      out.write("         var Isnumber = /^\\d+$/;\n");
      out.write("         function FristNameValid(){\n");
      out.write("             var firstName = document.forms[\"registration\"][\"first_name\"].value;\n");
      out.write("            \n");
      out.write("            if(!(nameRegex.test(firstName))){\n");
      out.write("                document.getElementById(\"error1\").innerHTML = \"Please Enter Valid Name\";\n");
      out.write("                 document.getElementById(\"first_name\").value=\"\";\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("            else{\n");
      out.write("                document.getElementById(\"error1\").innerHTML=\"\";\n");
      out.write("                 return true;\n");
      out.write("            }\n");
      out.write("         }\n");
      out.write("         function SecondNameValid(){\n");
      out.write("            var lastName = document.forms[\"registration\"][\"last_name\"].value;\n");
      out.write("            if(!(nameRegex.test(lastName))){\n");
      out.write("                document.getElementById(\"error2\").innerHTML = \"Please Enter Valid Name\";\n");
      out.write("                 document.getElementById(\"lastName\").value=\"\";\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("            else{\n");
      out.write("                document.getElementById(\"error2\").innerHTML=\"\";\n");
      out.write("                 return true;\n");
      out.write("            }\n");
      out.write("         } \n");
      out.write("         function EmailValid(){\n");
      out.write("             var email = document.forms[\"registration\"][\"email\"].value;\n");
      out.write("             if(!(emailRegex.test(email))){\n");
      out.write("                document.getElementById(\"error3\").innerHTML = \"Please Enter Valid Email\";\n");
      out.write("                 document.getElementById(\"email\").value=\"\";\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("            else{\n");
      out.write("                document.getElementById(\"error3\").innerHTML=\"\";\n");
      out.write("                 return true;\n");
      out.write("            }\n");
      out.write("         }\n");
      out.write("         function PassValid(){\n");
      out.write("              var Password = document.getElementById(\"Password\").value;\n");
      out.write("              if(Password.length < 6){\n");
      out.write("                  document.getElementById(\"error4\").innerHTML = \"Password less 6 Charector\";\n");
      out.write("                 document.getElementById(\"Password\").value=\"\";\n");
      out.write("                return false;\n");
      out.write("              }\n");
      out.write("              else{\n");
      out.write("                document.getElementById(\"error4\").innerHTML=\"\";\n");
      out.write("                 return true;\n");
      out.write("                }\n");
      out.write("         }\n");
      out.write("         function SemPassValid(){\n");
      out.write("             var Password = document.getElementById(\"Password\").value;\n");
      out.write("             var cPassword = document.getElementById(\"Conform\").value;\n");
      out.write("              if(Password != cPassword ){\n");
      out.write("                  document.getElementById(\"error5\").innerHTML = \"Enter a sem Password\";\n");
      out.write("                 document.getElementById(\"Conform\").value=\"\";\n");
      out.write("                return false;\n");
      out.write("              }\n");
      out.write("              else{\n");
      out.write("                document.getElementById(\"error5\").innerHTML=\"\";\n");
      out.write("                 return true;\n");
      out.write("                }\n");
      out.write("         }\n");
      out.write("         function NumberValid(){\n");
      out.write("             var Number = document.forms[\"registration\"][\"Number\"].value;\n");
      out.write("             if(!(Isnumber.test(Number)) || Number.length != 10){\n");
      out.write("                 document.getElementById(\"error6\").innerHTML = \"Enter a Valid Number\";\n");
      out.write("                 document.getElementById(\"Number\").value=\"\";\n");
      out.write("                return false;\n");
      out.write("             }\n");
      out.write("             else{\n");
      out.write("                document.getElementById(\"error6\").innerHTML=\"\";\n");
      out.write("                 return true;  \n");
      out.write("             }\n");
      out.write("         }\n");
      out.write("         \n");
      out.write("    function validateForm() {\n");
      out.write("            if(FristNameValid() && SecondNameValid() && EmailValid() && PassValid() && SemPassValid() )  {\n");
      out.write("             return true; \n");
      out.write("            }\n");
      out.write("            else{\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
