/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-07-14 11:08:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


        String User_id = (String) session.getAttribute("User_id");
        if (User_id != null) {
      out.write("\n");
      out.write("<script>\n");
      out.write("    document.getElementById(\"user\").addEventListener(\"load\", myFunction);\n");
      out.write("    function myFunction()\n");
      out.write("    {\n");
      out.write("        document.getElementById(\"user\").className = \"user-panel\";\n");
      out.write("        document.getElementById(\"User-drop\").className = \"user-dropdown\";\n");
      out.write("        document.getElementById(\"Contener\").className = \"dropdown-content\";\n");
      out.write("//              document.getElementById(\"User-drop\").addEventListener(\"mouseover\", Dropdown);\n");
      out.write("        document.getElementById(\"User-drop\").setAttribute(\"href\", \"\");\n");
      out.write("        document.getElementById(\"sin\").setAttribute(\"href\", \"\");\n");
      out.write("        Dropdown(\"UserInfo\", \"Admin.jsp\");\n");
      out.write("        Dropdown(\"Logout\", \"Logout.jsp\");\n");
      out.write("\n");
      out.write("    }\n");
      out.write("    function Dropdown(text, url) {\n");
      out.write("        const node = document.createElement(\"a\");\n");
      out.write("        // Create a text node:\n");
      out.write("        node.setAttribute(\"href\", url)\n");
      out.write("        const textnode = document.createTextNode(text);\n");
      out.write("        // Append the text node to the \"li\" node:\n");
      out.write("        node.appendChild(textnode);\n");
      out.write("        // Append the \"li\" node to the list:\n");
      out.write("        document.getElementById(\"Contener\").appendChild(node);\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("\n");
}
      out.write("\n");
      out.write("<!--<style>\n");
      out.write("     .active {\n");
      out.write("        color: blue; /* Change color for demonstration */\n");
      out.write("    }\n");
      out.write("</style>-->\n");
      out.write("<section id=\"header\">\n");
      out.write("    <a href=\"#\"><img src=\"img/BookLogo.png\" class=\"logo log\" /></a>\n");
      out.write("\n");
      out.write("    <label\n");
      out.write("        for=\"default-search\"\n");
      out.write("        class=\"mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white\"\n");
      out.write("        >Search</label\n");
      out.write("    >\n");
      out.write("    <div class=\"relative\">\n");
      out.write("        <div\n");
      out.write("            class=\"absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none\"\n");
      out.write("            >\n");
      out.write("            <svg\n");
      out.write("                class=\"w-4 h-4 text-gray-500 dark:text-gray-400\"\n");
      out.write("                aria-hidden=\"true\"\n");
      out.write("                xmlns=\"http://www.w3.org/2000/svg\"\n");
      out.write("                fill=\"none\"\n");
      out.write("                viewBox=\"0 0 20 20\"\n");
      out.write("                >\n");
      out.write("                <path\n");
      out.write("                    stroke=\"currentColor\"\n");
      out.write("                    stroke-linecap=\"round\"\n");
      out.write("                    stroke-linejoin=\"round\"\n");
      out.write("                    stroke-width=\"2\"\n");
      out.write("                    d=\"m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z\"\n");
      out.write("                    />\n");
      out.write("            </svg>\n");
      out.write("        </div>\n");
      out.write("        <form action=\"Search\">\n");
      out.write("        <input\n");
      out.write("            type=\"search\"\n");
      out.write("            id=\"default-search\"\n");
      out.write("            name=\"search\"\n");
      out.write("            class=\"block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500\"\n");
      out.write("            placeholder=\"Search Your Books...\"\n");
      out.write("            required\n");
      out.write("            />\n");
      out.write("        <button\n");
      out.write("            type=\"submit\"\n");
      out.write("            style=\"background-color: hsl(229, 100%, 76%); color: black\"\n");
      out.write("            class=\"text-white absolute end-2.5 bottom-2.5 bg-gray-700 hover:bg-gray-800 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800\"\n");
      out.write("            >\n");
      out.write("            Search\n");
      out.write("        </button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div>\n");
      out.write("        <ul id=\"navbar\">\n");
      out.write("            <li><a class=\"active\" href=\"Home\">Home</a></li>\n");
      out.write("            <li><a href=\"Discounts\">Discounts</a></li>\n");
      out.write("            <li><a href=\"NewBooks.jsp\">NewBooks</a></li>\n");
      out.write("            <li><a href=\"AllBook.jsp\">AllBook</a></li>\n");
      out.write("            <li><a href=\"Contact.jsp\">Contact</a></li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"Request.jsp\">BookRequest</a>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("            <li id=\"lg-bag\">\n");
      out.write("                <a href=\"CartServlet\"><i class=\"far fa-shopping-bag\"></i></a>\n");
      out.write("            </li>\n");
      out.write("            <a href=\"#\" id=\"close1\"><i class=\"far fa-times\"></i></a>\n");
      out.write("        </ul>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"mobile\">\n");
      out.write("        <a href=\"cart.jsp\"><i class=\"far fa-shopping-bag\"></i></a>\n");
      out.write("        <i id=\"bar\" class=\"fas fa-outdent\"></i>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"user\" id=\"user\" >\n");
      out.write("        <a href=\"Sign.jsp\" class=\"active\" id=\"User-drop\">\n");
      out.write("            <svg\n");
      out.write("                class=\"w-6 h-6 text-gray-800 dark:text-white\"\n");
      out.write("                aria-hidden=\"true\"\n");
      out.write("                xmlns=\"http://www.w3.org/2000/svg\"\n");
      out.write("                width=\"24\"\n");
      out.write("                height=\"24\"\n");
      out.write("                fill=\"currentColor\"\n");
      out.write("                viewBox=\"0 0 24 24\"\n");
      out.write("                >\n");
      out.write("                <path\n");
      out.write("                    fill-rule=\"evenodd\"\n");
      out.write("                    d=\"M12 20a7.966 7.966 0 0 1-5.002-1.756l.002.001v-.683c0-1.794 1.492-3.25 3.333-3.25h3.334c1.84 0 3.333 1.456 3.333 3.25v.683A7.966 7.966 0 0 1 12 20ZM2 12C2 6.477 6.477 2 12 2s10 4.477 10 10c0 5.5-4.44 9.963-9.932 10h-.138C6.438 21.962 2 17.5 2 12Zm10-5c-1.84 0-3.333 1.455-3.333 3.25S10.159 13.5 12 13.5c1.84 0 3.333-1.455 3.333-3.25S13.841 7 12 7Z\"\n");
      out.write("                    clip-rule=\"evenodd\"\n");
      out.write("                    />\n");
      out.write("            </svg>\n");
      out.write("            <div id=\"Contener\"></div>\n");
      out.write("        </a>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!--<script>\n");
      out.write("    // Get all anchor tags inside the navbar\n");
      out.write("    const navLinks = document.querySelectorAll('#navbar a');\n");
      out.write("\n");
      out.write("    // Add click event listener to each anchor tag\n");
      out.write("    navLinks.forEach(link => {\n");
      out.write("        link.addEventListener('click', function (event) {\n");
      out.write("            event.preventDefault(); // Prevent default behavior of the link\n");
      out.write("\n");
      out.write("            // Remove 'active' class from all links\n");
      out.write("            navLinks.forEach(link => {\n");
      out.write("                link.classList.remove('active');\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            // Add 'active' class to the clicked link\n");
      out.write("            this.classList.add('active');\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("</script>-->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
