/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-03-16 06:34:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("        <style>\n");
      out.write("            html {\n");
      out.write("              height: 100%;\n");
      out.write("            }\n");
      out.write("            body {\n");
      out.write("              margin:0;\n");
      out.write("              padding:0;\n");
      out.write("              font-family: sans-serif;\n");
      out.write("              background: linear-gradient(#141e30, #243b55);\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .login-box {\n");
      out.write("              position: absolute;\n");
      out.write("              top: 50%;\n");
      out.write("              left: 50%;\n");
      out.write("              width: 400px;\n");
      out.write("              padding: 40px;\n");
      out.write("              transform: translate(-50%, -50%);\n");
      out.write("              background: rgba(0,0,0,.5);\n");
      out.write("              box-sizing: border-box;\n");
      out.write("              box-shadow: 0 15px 25px rgba(0,0,0,.6);\n");
      out.write("              border-radius: 10px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .login-box h2 {\n");
      out.write("              margin: 0 0 30px;\n");
      out.write("              padding: 0;\n");
      out.write("              color: white;\n");
      out.write("              text-align: center;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .login-box .user-box {\n");
      out.write("              position: relative;\n");
      out.write("              color: white;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .login-box .user-box input {\n");
      out.write("              width: 100%;\n");
      out.write("              padding: 10px 0;\n");
      out.write("              font-size: 16px;\n");
      out.write("              color: white;\n");
      out.write("              margin-bottom: 30px;\n");
      out.write("              border: none;\n");
      out.write("              border-bottom: 1px solid #fff;\n");
      out.write("              outline: none;\n");
      out.write("              background: transparent;\n");
      out.write("            }\n");
      out.write("            .login-box .user-box label {\n");
      out.write("              position: absolute;\n");
      out.write("              top:0;\n");
      out.write("              left: 0;\n");
      out.write("              padding: 10px 0;\n");
      out.write("              font-size: 16px;\n");
      out.write("              color: #fff;\n");
      out.write("              pointer-events: none;\n");
      out.write("              transition: .5s;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .login-box .user-box input:focus ~ label,\n");
      out.write("            .login-box .user-box input:valid ~ label {\n");
      out.write("              top: -20px;\n");
      out.write("              left: 0;\n");
      out.write("              color: white;\n");
      out.write("              font-size: 12px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .login-box form a {\n");
      out.write("              position: relative;\n");
      out.write("              display: inline-block;\n");
      out.write("              padding: 10px 20px;\n");
      out.write("              color: white;\n");
      out.write("              font-size: 16px;\n");
      out.write("              text-decoration: none;\n");
      out.write("              text-transform: uppercase;\n");
      out.write("              overflow: hidden;\n");
      out.write("              transition: .5s;\n");
      out.write("              margin-top: 40px;\n");
      out.write("              letter-spacing: 4px\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .login-box a:hover {\n");
      out.write("              background: #03e9f4;\n");
      out.write("              color: #fff;\n");
      out.write("              border-radius: 5px;\n");
      out.write("              box-shadow: 0 0 5px #03e9f4,\n");
      out.write("                          0 0 25px #03e9f4,\n");
      out.write("                          0 0 50px #03e9f4,\n");
      out.write("                          0 0 100px #03e9f4;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .login-box a .span {\n");
      out.write("              position: absolute;\n");
      out.write("              display: block;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .login-box a .span:nth-child(1) {\n");
      out.write("              top: 0;\n");
      out.write("              left: -100%;\n");
      out.write("              width: 100%;\n");
      out.write("              height: 2px;\n");
      out.write("              background: linear-gradient(90deg, transparent, #03e9f4);\n");
      out.write("              animation: btn-anim1 1s linear infinite;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            @keyframes btn-anim1 {\n");
      out.write("              0% {\n");
      out.write("                left: -100%;\n");
      out.write("              }\n");
      out.write("              50%,100% {\n");
      out.write("                left: 100%;\n");
      out.write("              }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .login-box a .span:nth-child(2) {\n");
      out.write("              top: -100%;\n");
      out.write("              right: 0;\n");
      out.write("              width: 2px;\n");
      out.write("              height: 100%;\n");
      out.write("              background: linear-gradient(180deg, transparent, #03e9f4);\n");
      out.write("              animation: btn-anim2 1s linear infinite;\n");
      out.write("              animation-delay: .25s\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            @keyframes btn-anim2 {\n");
      out.write("              0% {\n");
      out.write("                top: -100%;\n");
      out.write("              }\n");
      out.write("              50%,100% {\n");
      out.write("                top: 100%;\n");
      out.write("              }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .login-box a .span:nth-child(3) {\n");
      out.write("              bottom: 0;\n");
      out.write("              right: -100%;\n");
      out.write("              width: 100%;\n");
      out.write("              height: 2px;\n");
      out.write("              background: linear-gradient(270deg, transparent, #03e9f4);\n");
      out.write("              animation: btn-anim3 1s linear infinite;\n");
      out.write("              animation-delay: .5s\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            @keyframes btn-anim3 {\n");
      out.write("              0% {\n");
      out.write("                right: -100%;\n");
      out.write("              }\n");
      out.write("              50%,100% {\n");
      out.write("                right: 100%;\n");
      out.write("              }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .login-box a .span:nth-child(4) {\n");
      out.write("              bottom: -100%;\n");
      out.write("              left: 0;\n");
      out.write("              width: 2px;\n");
      out.write("              height: 100%;\n");
      out.write("              background: linear-gradient(360deg, transparent, #03e9f4);\n");
      out.write("              animation: btn-anim4 1s linear infinite;\n");
      out.write("              animation-delay: .75s\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            @keyframes btn-anim4 {\n");
      out.write("              0% {\n");
      out.write("                bottom: -100%;\n");
      out.write("              }\n");
      out.write("              50%,100% {\n");
      out.write("                bottom: 100%;\n");
      out.write("              }\n");
      out.write("            }\n");
      out.write("            #error1,#error2{\n");
      out.write("                    margin: -25px 0px 18px 119px;\n");
      out.write("                    color: #f20808;\n");
      out.write("            }\n");
      out.write("            #sub{\n");
      out.write("                background-color:black ;\n");
      out.write("                color: white;\n");
      out.write("                border: none;\n");
      out.write("            }\n");
      out.write("            #sub:hover{\n");
      out.write("                 background-color: #03e9f4 ;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("         ");

            String user = null;
            String userName = null;
            String userEmail = null;
            if(session.getAttribute("User") == null){
                response.sendRedirect("index.jsp");
               }else{
               user = (String) session.getAttribute("User");
               userName = (String) session.getAttribute("UserName");
               userEmail = (String) session.getAttribute("UserEmail");

            } 
               
        
      out.write("\n");
      out.write("        <div class=\"login-box\">\n");
      out.write("            <h2>User Information</h2>\n");
      out.write("            <table>\n");
      out.write("                <tr>\n");
      out.write("                    <td class=\"user-box\">User Roll :</td><td class=\"user-box\">");
      out.print( user );
      out.write("</td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td class=\"user-box\">User Name :</td><td class=\"user-box\">");
      out.print( userName );
      out.write("</td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td class=\"user-box\">User Email:</td><td class=\"user-box\">");
      out.print( userEmail );
      out.write("</td>\n");
      out.write("                </tr>\n");
      out.write("            </table>    \n");
      out.write("        </div>\n");
      out.write("       \n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
