/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-04-15 04:51:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class searchBook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

    String searchKey = request.getParameter("searchKey");
    String searchKeyword = request.getParameter("searchKeyword");

    Connection conn = null;
    PreparedStatement stmt = null;
    ResultSet rs = null;

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/parikshit_20", "root", "");

        if (searchKey != null && searchKeyword != null) {
            String sql = "";
            if ("book_id".equals(searchKey)) {
                sql = "SELECT * FROM book WHERE bookId LIKE ?";
            } else if ("catalogue_id".equals(searchKey)) {
                sql = "SELECT * FROM book WHERE catalogueId LIKE ?";
            } else if ("book_title".equals(searchKey)) {
                sql = "SELECT * FROM book WHERE title LIKE ?";
            } else if ("author_name".equals(searchKey)) {
                sql = "SELECT * FROM book WHERE author LIKE ?";
            } else if ("price".equals(searchKey)) {
                sql = "SELECT * FROM book WHERE price LIKE ?";
            } else if ("quantity".equals(searchKey)) {
                sql = "SELECT * FROM book WHERE quantity LIKE ?";
            } else if ("isbn_no".equals(searchKey)) {
                sql = "SELECT * FROM book WHERE ISBN LIKE ?";
            } else if ("publisher".equals(searchKey)) {
                sql = "SELECT * FROM book WHERE publisher LIKE ?";
            } else if ("edition_year".equals(searchKey)) {
                sql = "SELECT * FROM book WHERE editionYear LIKE ?";
            } 

            stmt = conn.prepareStatement(sql);
            stmt.setString(1, "%" + searchKeyword + "%");
            rs = stmt.executeQuery();
        }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            background-color: #f2f2f2;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .container {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: stretch;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .menu-bar {\n");
      out.write("            background-color: #607d8b;\n");
      out.write("            color: #fff;\n");
      out.write("            padding: 20px;\n");
      out.write("            margin-right: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .menu-bar a {\n");
      out.write("            display: block;\n");
      out.write("            color: #fff;\n");
      out.write("            text-decoration: none;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .menu-bar a:hover {\n");
      out.write("            background-color: #455a64;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .content {\n");
      out.write("            background-color: #fff;\n");
      out.write("            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);\n");
      out.write("            margin: auto;\n");
      out.write("            padding: 30px;\n");
      out.write("            max-width: 1000px;\n");
      out.write("            border-radius: 5px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        h1 {\n");
      out.write("            color: #607d8b;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        th, td {\n");
      out.write("            padding: 10px;\n");
      out.write("            border-bottom: 1px solid #ccc;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        th {\n");
      out.write("            background-color: #f2f2f2;\n");
      out.write("            color: #607d8b;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        td {\n");
      out.write("            background-color: #fff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        input {\n");
      out.write("            width: 80%;\n");
      out.write("            padding: 10px;\n");
      out.write("            margin-top: 20px;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            border: 1px solid #ccc;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .custom-radio {\n");
      out.write("            display: inline-block;\n");
      out.write("            margin-right: 8px;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .custom-radio input[type=\"radio\"] {\n");
      out.write("            position: relative;\n");
      out.write("            display: inline-block;\n");
      out.write("            width: 18px;\n");
      out.write("            height: 18px;\n");
      out.write("            border: 2px solid #666;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            cursor: pointer;\n");
      out.write("            vertical-align: middle;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .custom-radio input[type=\"radio\"]:checked + .radio-icon {\n");
      out.write("            background-color: #202c40;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .custom-radio label {\n");
      out.write("            vertical-align: middle;\n");
      out.write("            color: #607d8b;\n");
      out.write("            font-size: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button {\n");
      out.write("            color: #607d8b;\n");
      out.write("            background: #fff;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-size: 24px;\n");
      out.write("            border: none;\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button i.fa-search {\n");
      out.write("            font-size: 30px;\n");
      out.write("            color: #607d8b;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button:hover i.fa-search {\n");
      out.write("            color: #384951 !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("    <script>\n");
      out.write("        function showSearch() {\n");
      out.write("            var input = document.getElementById(\"searchInput\");\n");
      out.write("            var button = document.getElementById(\"searchButton\");\n");
      out.write("            input.style.display = \"inline-block\";\n");
      out.write("            button.style.display = \"inline-block\";\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "index.jsp", out, false);
      out.write("\n");
      out.write("        <div class=\"content\">\n");
      out.write("            <h1>Search Book</h1>\n");
      out.write("            <form action=\"#\" method=\"post\">\n");
      out.write("                 <div class=\"custom-radio\">\n");
      out.write("                        <input type=\"radio\" id=\"book_id\" value=\"book_id\" name=\"searchKey\" onclick=\"showSearch()\">\n");
      out.write("                        <span class=\"radio-icon\"></span>\n");
      out.write("                        <label for=\"book_id\">Book Id</label>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"custom-radio\">\n");
      out.write("                        <input type=\"radio\" id=\"catalogue_id\" value=\"catalogue_id\" name=\"searchKey\" onclick=\"showSearch()\">\n");
      out.write("                        <span class=\"radio-icon\"></span>\n");
      out.write("                        <label for=\"catalogue_id\">Catalogue Id</label>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"custom-radio\">\n");
      out.write("                        <input type=\"radio\" id=\"book_title\" value=\"book_title\" name=\"searchKey\" onclick=\"showSearch()\">\n");
      out.write("                        <span class=\"radio-icon\"></span>\n");
      out.write("                        <label for=\"book_title\">Book Title</label>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"custom-radio\">\n");
      out.write("                        <input type=\"radio\" id=\"author_name\" value=\"author_name\" name=\"searchKey\" onclick=\"showSearch()\">\n");
      out.write("                        <span class=\"radio-icon\"></span>\n");
      out.write("                        <label for=\"author_name\">Author Name</label>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"custom-radio\">\n");
      out.write("                        <input type=\"radio\" id=\"price\" value=\"price\" name=\"searchKey\" onclick=\"showSearch()\">\n");
      out.write("                        <span class=\"radio-icon\"></span>\n");
      out.write("                        <label for=\"price\">Price</label>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"custom-radio\">\n");
      out.write("                        <input type=\"radio\" id=\"quantity\" value=\"quantity\" name=\"searchKey\" onclick=\"showSearch()\">\n");
      out.write("                        <span class=\"radio-icon\"></span>\n");
      out.write("                        <label for=\"quantity\">Quantity</label>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"custom-radio\">\n");
      out.write("                        <input type=\"radio\" id=\"isbn_no\" value=\"isbn_no\" name=\"searchKey\" onclick=\"showSearch()\">\n");
      out.write("                        <span class=\"radio-icon\"></span>\n");
      out.write("                        <label for=\"isbn_no\">ISBN No</label>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"custom-radio\">\n");
      out.write("                        <input type=\"radio\" id=\"publisher\" value=\"publisher\" name=\"searchKey\" onclick=\"showSearch()\">\n");
      out.write("                        <span class=\"radio-icon\"></span>\n");
      out.write("                        <label for=\"publisher\">Publisher</label>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"custom-radio\">\n");
      out.write("                        <input type=\"radio\" id=\"edition_year\" value=\"edition_year\" name=\"searchKey\" onclick=\"showSearch()\">\n");
      out.write("                        <span class=\"radio-icon\"></span>\n");
      out.write("                        <label for=\"edition_year\">Edition Year</label>\n");
      out.write("                    </div>\n");
      out.write("                    <input type=\"text\" id=\"searchInput\" name=\"searchKeyword\" placeholder=\"Enter data to search...\">\n");
      out.write("                    <button type=\"submit\" id=\"searchButton\"><i class=\"fas fa-search\"></i></button>\n");
      out.write("                </form>\n");
      out.write("            <table>\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>Book Id</th>\n");
      out.write("                        <th>Catalogue Id</th>\n");
      out.write("                        <th>Book Title</th>\n");
      out.write("                        <th>Author Name</th>\n");
      out.write("                        <th>Price</th>\n");
      out.write("                        <th>Quantity</th>\n");
      out.write("                        <th>ISBN No</th>\n");
      out.write("                        <th>Publisher</th>\n");
      out.write("                        <th>Edition Year</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                    ");
 
                        while (rs != null && rs.next()) {
                    
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>");
      out.print( rs.getString("bookId") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("catalogueId") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("title") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("author") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("price") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("quantity") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("ISBN") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("publisher") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("editionYear") );
      out.write("</td>\n");
      out.write("                    </tr>\n");
      out.write("                    ");
 
                        } 
                    
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");

    } catch (Exception e) {
        e.printStackTrace();
    } finally {
        try {
            if (rs != null) {
                rs.close();
            }
            if (stmt != null) {
                stmt.close();
            }
            if (conn != null) {
                conn.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
