/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-03-28 03:15:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("        <link\n");
      out.write("            rel=\"stylesheet\"\n");
      out.write("            href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\"\n");
      out.write("            />\n");
      out.write("        <link\n");
      out.write("            href=\"https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css\"\n");
      out.write("            rel=\"stylesheet\"\n");
      out.write("            />\n");
      out.write("        <link rel=\"stylesheet\" href=\"style.css\" />\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <section id=\"header\">\n");
      out.write("            <a href=\"#\"><img src=\"img/BookLogo.png\" class=\"logo log\" /></a>\n");
      out.write("\n");
      out.write("            <label\n");
      out.write("                for=\"default-search\"\n");
      out.write("                class=\"mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white\"\n");
      out.write("                >Search</label\n");
      out.write("            >\n");
      out.write("            <div class=\"relative\">\n");
      out.write("                <div\n");
      out.write("                    class=\"absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none\"\n");
      out.write("                    >\n");
      out.write("                    <svg\n");
      out.write("                        class=\"w-4 h-4 text-gray-500 dark:text-gray-400\"\n");
      out.write("                        aria-hidden=\"true\"\n");
      out.write("                        xmlns=\"http://www.w3.org/2000/svg\"\n");
      out.write("                        fill=\"none\"\n");
      out.write("                        viewBox=\"0 0 20 20\"\n");
      out.write("                        >\n");
      out.write("                    <path\n");
      out.write("                        stroke=\"currentColor\"\n");
      out.write("                        stroke-linecap=\"round\"\n");
      out.write("                        stroke-linejoin=\"round\"\n");
      out.write("                        stroke-width=\"2\"\n");
      out.write("                        d=\"m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z\"\n");
      out.write("                        />\n");
      out.write("                    </svg>\n");
      out.write("                </div>\n");
      out.write("                <input\n");
      out.write("                    style=\"width: 350px\"\n");
      out.write("                    type=\"search\"\n");
      out.write("                    id=\"default-search\"\n");
      out.write("                    class=\"block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500\"\n");
      out.write("                    placeholder=\"Search Your Books...\"\n");
      out.write("                    required\n");
      out.write("                    />\n");
      out.write("                <button\n");
      out.write("                    type=\"submit\"\n");
      out.write("                    style=\"background-color: hsl(229, 100%, 76%); color: black\"\n");
      out.write("                    class=\"text-white absolute end-2.5 bottom-2.5 bg-gray-700 hover:bg-gray-800 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800\"\n");
      out.write("                    >\n");
      out.write("                    Search\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <ul id=\"navbar\">\n");
      out.write("                    <li><a class=\"active\" href=\"index.html\">Home</a></li>\n");
      out.write("                    <li><a href=\"/DiscountF/Discounts.html\">Discounts%</a></li>\n");
      out.write("                    <li><a href=\"/NewBookF/NewBooks.html\">NewBooks</a></li>\n");
      out.write("                    <li><a href=\"/AllBookF/AllBook.html\">AllBook</a></li>\n");
      out.write("                    <li><a href=\"/Contact.html\">Contact</a></li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"/Request.html\">BookRequest</a>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li id=\"lg-bag\">\n");
      out.write("                        <a href=\"cart.html\"><i class=\"far fa-shopping-bag\"></i></a>\n");
      out.write("                    </li>\n");
      out.write("                    <a href=\"#\" id=\"close1\"><i class=\"far fa-times\"></i></a>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"mobile\">\n");
      out.write("                <a href=\"cart.html\"><i class=\"far fa-shopping-bag\"></i></a>\n");
      out.write("                <i id=\"bar\" class=\"fas fa-outdent\"></i>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"user\" style=\"margin-left: 20px\">\n");
      out.write("                <a href=\"Sign.html\" class=\"active\">\n");
      out.write("                    <svg\n");
      out.write("                        class=\"w-6 h-6 text-gray-800 dark:text-white\"\n");
      out.write("                        aria-hidden=\"true\"\n");
      out.write("                        xmlns=\"http://www.w3.org/2000/svg\"\n");
      out.write("                        width=\"24\"\n");
      out.write("                        height=\"24\"\n");
      out.write("                        fill=\"currentColor\"\n");
      out.write("                        viewBox=\"0 0 24 24\"\n");
      out.write("                        >\n");
      out.write("                    <path\n");
      out.write("                        fill-rule=\"evenodd\"\n");
      out.write("                        d=\"M12 20a7.966 7.966 0 0 1-5.002-1.756l.002.001v-.683c0-1.794 1.492-3.25 3.333-3.25h3.334c1.84 0 3.333 1.456 3.333 3.25v.683A7.966 7.966 0 0 1 12 20ZM2 12C2 6.477 6.477 2 12 2s10 4.477 10 10c0 5.5-4.44 9.963-9.932 10h-.138C6.438 21.962 2 17.5 2 12Zm10-5c-1.84 0-3.333 1.455-3.333 3.25S10.159 13.5 12 13.5c1.84 0 3.333-1.455 3.333-3.25S13.841 7 12 7Z\"\n");
      out.write("                        clip-rule=\"evenodd\"\n");
      out.write("                        />\n");
      out.write("                    </svg>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section id=\"hero\">\n");
      out.write("            <h1 class=\"texti\" style=\"color: rgb(227, 252, 252)\">\n");
      out.write("                WELCOME TO<br /><span> ONLINE BOOK STORE</span>\n");
      out.write("            </h1>\n");
      out.write("            <p class=\"texti\" style=\"color: rgb(212, 212, 255)\">\n");
      out.write("                Save more Book with coupons & up to 70% off!\n");
      out.write("            </p>\n");
      out.write("            <button class=\"texti\">\n");
      out.write("                <a href=\"AllBook.html\" class=\"main_btn\">Learn More</a>\n");
      out.write("            </button>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section id=\"feature\" class=\"section-p1\">\n");
      out.write("            <div class=\"fe-box\">\n");
      out.write("                <img src=\"img/f1.png\" alt=\"\" />\n");
      out.write("                <h6>free</h6>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"fe-box\">\n");
      out.write("                <img src=\"img/f2.png\" alt=\"\" />\n");
      out.write("                <h6>Save Time</h6>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"fe-box\">\n");
      out.write("                <img src=\"img/f3.png\" alt=\"\" />\n");
      out.write("                <h6>Save Money</h6>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"fe-box\">\n");
      out.write("                <img src=\"img/f4.png\" alt=\"\" />\n");
      out.write("                <h6>Promotions</h6>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"fe-box\">\n");
      out.write("                <img src=\"img/f5.png\" alt=\"\" />\n");
      out.write("                <h6>Heppy Sell</h6>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"fe-box\">\n");
      out.write("                <img src=\"img/f6.png\" alt=\"\" />\n");
      out.write("                <h6>F24/7 Support</h6>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section id=\"products1\" class=\"section-p1\">\n");
      out.write("            <h2>Featured Books</h2>\n");
      out.write("            <p>Best sell book in site</p>\n");
      out.write("            <div class=\"pro-container\">\n");
      out.write("                <div class=\"pro\">\n");
      out.write("                    <img src=\"img/arrival_1.jpg\" alt=\"\" />\n");
      out.write("                    <div class=\"des\">\n");
      out.write("                        <span>Best Book</span>\n");
      out.write("                        <h5>The Gever lois lowry</h5>\n");
      out.write("                        <div class=\"star\">\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>₹1078</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"Add.html\"><i class=\"fal fa-shopping-cart cart\"></i></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pro\">\n");
      out.write("                    <img src=\"img/arrival_2.jpg\" alt=\"\" />\n");
      out.write("                    <div class=\"des\">\n");
      out.write("                        <span>Best Book</span>\n");
      out.write("                        <h5>The Wright Brathers</h5>\n");
      out.write("                        <div class=\"star\">\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>₹1078</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"Add.html\"><i class=\"fal fa-shopping-cart cart\"></i></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pro\">\n");
      out.write("                    <img src=\"img/arrival_3.jpg\" alt=\"\" />\n");
      out.write("                    <div class=\"des\">\n");
      out.write("                        <span>Best Book</span>\n");
      out.write("                        <h5>Radiacal Gardening</h5>\n");
      out.write("                        <div class=\"star\">\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>₹1078</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"Add.html\"><i class=\"fal fa-shopping-cart cart\"></i></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pro\">\n");
      out.write("                    <img src=\"img/arrival_4.jpg\" alt=\"\" />\n");
      out.write("                    <div class=\"des\">\n");
      out.write("                        <span>Best Book</span>\n");
      out.write("                        <h5>Red Queen</h5>\n");
      out.write("                        <div class=\"star\">\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>₹1078</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"Add.html\"><i class=\"fal fa-shopping-cart cart\"></i></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pro\">\n");
      out.write("                    <img src=\"img/arrival_5.jpg\" alt=\"\" />\n");
      out.write("                    <div class=\"des\">\n");
      out.write("                        <span>Best Book</span>\n");
      out.write("                        <h5></h5>\n");
      out.write("                        <div class=\"star\">\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>₹1078</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"Add.html\"><i class=\"fal fa-shopping-cart cart\"></i></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pro\">\n");
      out.write("                    <img src=\"img/arrival_6.jpg\" alt=\"\" />\n");
      out.write("                    <div class=\"des\">\n");
      out.write("                        <span>Best Book</span>\n");
      out.write("                        <h5></h5>\n");
      out.write("                        <div class=\"star\">\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>₹1078</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"Add.html\"><i class=\"fal fa-shopping-cart cart\"></i></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pro\">\n");
      out.write("                    <img src=\"img/arrival_7.jpg\" alt=\"\" />\n");
      out.write("                    <div class=\"des\">\n");
      out.write("                        <span>Best Book</span>\n");
      out.write("                        <h5></h5>\n");
      out.write("                        <div class=\"star\">\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>₹1078</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"Add.html\"><i class=\"fal fa-shopping-cart cart\"></i></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pro\">\n");
      out.write("                    <img src=\"img/arrival_8.webp\" alt=\"\" />\n");
      out.write("                    <div class=\"des\">\n");
      out.write("                        <span>Best Book</span>\n");
      out.write("                        <h5></h5>\n");
      out.write("                        <div class=\"star\">\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>₹1078</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"Add.html\"><i class=\"fal fa-shopping-cart cart\"></i></a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section id=\"banner\" class=\"section-m1\">\n");
      out.write("            <a href=\"AllBookF/AllBook.html\"\n");
      out.write("               ><button class=\"normal\">Explore More</button></a\n");
      out.write("            >\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section id=\"products1\" class=\"section-p1\">\n");
      out.write("            <h2>New Arrivals</h2>\n");
      out.write("            <p>New Books Added in this site</p>\n");
      out.write("            <div class=\"pro-container\">\n");
      out.write("                <div class=\"pro\">\n");
      out.write("                    <img src=\"img/book_1.jpg\" alt=\"\" />\n");
      out.write("                    <div class=\"des\">\n");
      out.write("                        <span>Best Book</span>\n");
      out.write("                        <h5></h5>\n");
      out.write("                        <div class=\"star\">\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>₹1078</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"Add.html\"><i class=\"fal fa-shopping-cart cart\"></i></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pro\">\n");
      out.write("                    <img src=\"img/book_2.jpg\" alt=\"\" />\n");
      out.write("                    <div class=\"des\">\n");
      out.write("                        <span>Best Book</span>\n");
      out.write("                        <h5></h5>\n");
      out.write("                        <div class=\"star\">\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>₹1078</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"Add.html\"><i class=\"fal fa-shopping-cart cart\"></i></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pro\">\n");
      out.write("                    <img src=\"img/book_3.jpg\" alt=\"\" />\n");
      out.write("                    <div class=\"des\">\n");
      out.write("                        <span>Best Book</span>\n");
      out.write("                        <h5></h5>\n");
      out.write("                        <div class=\"star\">\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>₹1078</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"Add.html\"><i class=\"fal fa-shopping-cart cart\"></i></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pro\">\n");
      out.write("                    <img src=\"img/book_4.jpg\" alt=\"\" />\n");
      out.write("                    <div class=\"des\">\n");
      out.write("                        <span>Best Book</span>\n");
      out.write("                        <h5></h5>\n");
      out.write("                        <div class=\"star\">\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>₹1078</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"Add.html\"><i class=\"fal fa-shopping-cart cart\"></i></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pro\">\n");
      out.write("                    <img src=\"img/book_5.jpg\" alt=\"\" />\n");
      out.write("                    <div class=\"des\">\n");
      out.write("                        <span>Best Book</span>\n");
      out.write("                        <h5></h5>\n");
      out.write("                        <div class=\"star\">\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>₹1078</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"Add.html\"><i class=\"fal fa-shopping-cart cart\"></i></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pro\">\n");
      out.write("                    <img src=\"img/book_6.jpg\" alt=\"\" />\n");
      out.write("                    <div class=\"des\">\n");
      out.write("                        <span>Best Book</span>\n");
      out.write("                        <h5></h5>\n");
      out.write("                        <div class=\"star\">\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>₹1078</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"Add.html\"><i class=\"fal fa-shopping-cart cart\"></i></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pro\">\n");
      out.write("                    <img src=\"img/book_7.png\" alt=\"\" />\n");
      out.write("                    <div class=\"des\">\n");
      out.write("                        <span>Best Book</span>\n");
      out.write("                        <h5></h5>\n");
      out.write("                        <div class=\"star\">\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>₹1078</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"Add.html\"><i class=\"fal fa-shopping-cart cart\"></i></a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pro\">\n");
      out.write("                    <img src=\"img/book_8.png\" alt=\"\" />\n");
      out.write("                    <div class=\"des\">\n");
      out.write("                        <span>Best Book</span>\n");
      out.write("                        <h5></h5>\n");
      out.write("                        <div class=\"star\">\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                            <i class=\"fas fa-star\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h4>₹1078</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <a href=\"Add.html\"><i class=\"fal fa-shopping-cart cart\"></i></a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section id=\"banner3\">\n");
      out.write("            <div class=\"banner-box\">\n");
      out.write("                <h2>New Book SALE</h2>\n");
      out.write("                <h3>Book Collection -%50 OFF</h3>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"banner-box banner-box2\">\n");
      out.write("                <h2>NEW Book COLLECTION</h2>\n");
      out.write("                <h3>This Year/2024</h3>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section id=\"newsletter\" class=\"section-p1 section-m1\">\n");
      out.write("            <div class=\"newstext\">\n");
      out.write("                <h4>Sing Up For New Books</h4>\n");
      out.write("                <p>\n");
      out.write("                    Get E-mail updates about our latest Books\n");
      out.write("                    <span> & special offers.</span>\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form\">\n");
      out.write("                <input type=\"text \" placeholder=\"Your email address\" />\n");
      out.write("                <button class=\"normal\">Sing Up</button>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <footer class=\"section-p1\">\n");
      out.write("            <div class=\"col\">\n");
      out.write("                <img class=\"logo\" src=\"\" alt=\"\" />\n");
      out.write("                <h4>Contact</h4>\n");
      out.write("                <p>\n");
      out.write("                    <strong>Address:</strong> 562Wellington Road,Street 32.San Francisco\n");
      out.write("                </p>\n");
      out.write("                <p><strong>Phone:</strong> +01 2222 365/(+91) 01 2345 6789</p>\n");
      out.write("                <p><strong>Hours:</strong> 10:00 - 18:00,Mon - Sat</p>\n");
      out.write("                <div class=\"follow\">\n");
      out.write("                    <h4>Follow us</h4>\n");
      out.write("                    <div class=\"icon\">\n");
      out.write("                        <i class=\"fab fa-facebook-f\"></i>\n");
      out.write("                        <i class=\"fab fa-twitter\"></i>\n");
      out.write("                        <i class=\"fab fa-instagram\"></i>\n");
      out.write("                        <i class=\"fab fa-pinterest-p\"></i>\n");
      out.write("                        <i class=\"fab fa-youtube\"></i>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col\">\n");
      out.write("                <h4>About</h4>\n");
      out.write("                <a href=\"index.html\">Home</a>\n");
      out.write("                <a href=\"/DiscountF/Discounts.html\">Discounts%</a>\n");
      out.write("                <a href=\"/NewBookF/NewBooks.html\">NewBooks</a>\n");
      out.write("                <a href=\"/AllBookF/AllBook.html\">AllBook</a>\n");
      out.write("                <a href=\"Contact.html\">Contact Us</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col\">\n");
      out.write("                <h4>My Account</h4>\n");
      out.write("                <a href=\"Sign.html\">Sing In</a>\n");
      out.write("                <a href=\"cart.html\">View Cart</a>\n");
      out.write("                <a href=\"Request.html\">Request a Book</a>\n");
      out.write("                <a href=\"#\">Help</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col install\">\n");
      out.write("                <h4>install App</h4>\n");
      out.write("                <p>Form App Store or Google Play</p>\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <img src=\"img/app.jpg\" alt=\"\" />\n");
      out.write("                    <img src=\"img/play.jpg\" alt=\"\" />\n");
      out.write("                </div>\n");
      out.write("                <p>Secured Payment Getways</p>\n");
      out.write("                <img src=\"img/pay.png\" />\n");
      out.write("            </div>\n");
      out.write("            <div class=\"copyright\">\n");
      out.write("                <p>@ 2024, Mahir tech - HTML CSS Online Book Store</p>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("\n");
      out.write("        <script src=\"script.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
